name             'zabbix_ng'
maintainer       'Chris Aumann'
maintainer_email 'me@chr4.org'
license          'GNU Public License 3.0'
description      'Installs/Configures zabbix_ng'
long_description 'Installs/Configures zabbix_ng'
version          '1.0.2'
depends          'apt'
depends          'sudo'
